[project]
name = "enformer-embeddings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "enformer-pytorch>=0.8.11",
    "ipykernel>=6.29.5",
    "pandas>=2.3.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.3",
]
